version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    container_name: elasticsearch
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
    volumes:
      - ./hunspell:/etc/elasticsearch/hunspell

  grpc-service:
    container_name: grpc-service
    build:
      context: ./grpc-service
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    depends_on:
      - elasticsearch

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - grpc-service

  worker:
    container_name: worker
    build:
      context: ./worker
      dockerfile: Dockerfile
    depends_on:
      - grpc-service